pipeline {
    agent any
    tools{
        maven 'M2_HOME'
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
        stage('GIT'){
            steps{
                git branch: 'main',
                    url: 'https://github.com/Med-benabdallah/Devsecops-project.git'
            }
        }
        stage('Build + SonarQube') {
      steps {
        // Make sure Jenkins runs inside the repo root
        checkout scm

        // Run everything from the same folder that has pom.xml
        sh '''
          echo "Current directory:"
          pwd
          ls -la

          mvn -B -V -DskipTests clean verify sonar:sonar \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.token=$SONAR_TOKEN
        '''
      }
    }
        
        stage('Build (skip tests)') {
  steps {
    dir('student-man-main') {
      sh 'mvn -B -V -DskipTests clean package'
    }
  }
}

    }
}
