pipeline {
    agent any
    tools{
        maven 'M2_HOME'
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
        stage('GIT'){
            steps{
                git branch: 'main',
                    url: 'https://github.com/Med-benabdallah/Devsecops-project.git'
            }
        }
        stage('MVN SONARQUBE'){
            steps{
                echo 'SONARQUBE DONE!!!'
sh 'mvn  sonar:sonar'
            }
        }
        
        stage('Build (skip tests)') {
  steps {
    dir('student-man-main') {
      sh 'mvn -B -V -DskipTests clean package'
    }
  }
}

    }
}
