pipeline {
    agent any

    tools {
        maven 'M2_HOME'
    }

    environment {
        SONAR_TOKEN = credentials('devsecops') // 👈 linked credential
    }

    stages {
        stage('Build') {
            steps {
                dir('simple-java-maven-app') {
                    sh 'mvn -B clean install'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('simple-java-maven-app') {
                    withSonarQubeEnv('SonarQube') {
                        sh '''
                            mvn -B clean verify sonar:sonar \
                              -Dsonar.projectKey=my-app \
                              -Dsonar.host.url=http://localhost:9000 \
                              -Dsonar.token=$SONAR_TOKEN
                        '''
                    }
                }
            }
        }
        stage('Dependency Scan') {
            steps {
                dir('simple-java-maven-app') {
                    sh 'mvn org.owasp:dependency-check-maven:check -DfailOnCVSS=7'
                }
            }
        }
    }

    post {
        success {
            echo '✅ Pipeline completed successfully!'
        }
        failure {
            echo '❌ Pipeline failed — check the console output for details.'
        }
    }
}

